- name: Copying openstack.cnf file
  copy:
    src: openstack.cnf
    dest: /etc/my.cnf.d/openstack.cnf
    owner: root
    group: root
    mode: 644

  notify: Restarting database service

- name: Starting and enabling mariadb.service
  service:
    name: mariadb.service
    state: started
    enabled: true
